#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_origin_display        focused
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.1
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               shift
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config external_bar                 all:0:32

# general space settings
yabai -m config layout                       bsp
yabai -m config window_placement             first_child
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

# apps to not manage (ignore)
yabai -m rule --add app='^System Settings$'  manage=off
yabai -m rule --add app='^Messenger$'        manage=off
yabai -m rule --add app='^Archive Utility$'  manage=off
yabai -m rule --add app='^SpotMenu$'         manage=off

yabai -m space 1 --label 'terminal'
yabai -m space 2 --label 'browser'

# move apps to spaces
# yabai -m rule --add app="^kitty$"              space=1

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=4.0 &
