#!/usr/bin/env sh

alt - p : yabai -m window --focus stack.prev
alt - n : yabai -m window --focus stack.next || yabai -m window --focus stack.first

# 0x32 = backtick
cmd - 0x32 : ~/.config/skhd/toggle_space.sh 1

ctrl + shift - h : yabai -m window --focus west || yabai -m display --focus west
ctrl + shift - j : yabai -m window --focus south || yabai -m display --focus south
ctrl + shift - k : yabai -m window --focus north || yabai -m display --focus north
ctrl + shift - l : yabai -m window --focus east || yabai -m display --focus east

# swap
alt + shift - h : ~/.config/skhd/swap_and_focus.sh west
alt + shift - j : ~/.config/skhd/swap_and_focus.sh south
alt + shift - k : ~/.config/skhd/swap_and_focus.sh north
alt + shift - l : ~/.config/skhd/swap_and_focus.sh east

# resize
cmd + shift - h : yabai -m window west --resize right:-50:0 || yabai -m window --resize right:-50:0
cmd + shift - j : yabai -m window north --resize bottom:0:50 || yabai -m window --resize bottom:0:50
cmd + shift - k : yabai -m window south --resize top:0:-50 || yabai -m window --resize top:0:-50
cmd + shift - l : yabai -m window east --resize left:50:0 || yabai -m window --resize left:50:0

cmd + ctrl - right : yabai -m window --space next && yabai -m space --focus next
cmd + ctrl - left : yabai -m window --space prev && yabai -m space --focus prev
ctrl - right : yabai -m space --focus next
ctrl - left : yabai -m space --focus prev

# move to space
alt + shift - 1 : yabai -m window --space 1
alt + shift - 2 : yabai -m window --space 2
alt + shift - 3 : yabai -m window --space 3
alt + shift - 4 : yabai -m window --space 4
alt + shift - 5 : yabai -m window --space 5
alt + shift - 6 : yabai -m window --space 6
alt + shift - 7 : yabai -m window --space 7
alt + shift - 8 : yabai -m window --space 8
alt + shift - 9 : yabai -m window --space 9
alt + shift - 0 : yabai -m window --space 10

# go to space
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0 : yabai -m space --focus 10

ctrl + alt - return :  yabai -m window --grid 1:1:0:0:1:1 || yabai -m window --toggle zoom-fullscreen

# Launching Apps
cmd - return : /Applications/kitty.app/Contents/MacOS/kitty --single-instance --working-directory ~
cmd + shift - a : hs -c "NewArcWindow()"

# Layouts
cmd + alt - f : yabai -m space --layout float
cmd + alt - b : yabai -m space --layout bsp
cmd + alt - s : yabai -m space --layout stack

cmd + alt + shift - f : yabai -m config layout float
cmd + alt + shift - b : yabai -m config layout bsp
cmd + alt + shift - s : yabai -m config layout stack

# floating mode

# --grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>

# 1/2
ctrl + alt - h : yabai -m window --grid 1:2:0:0:1:1 # 1/2 left
ctrl + alt - l : yabai -m window --grid 1:2:1:0:1:1 # 1/2 right

# 1/4
ctrl + alt - r : yabai -m window --grid 2:2:0:0:1:1 # 1/4 top left
ctrl + alt - t : yabai -m window --grid 2:2:1:0:1:1 # 1/4 top right
ctrl + alt - f : yabai -m window --grid 2:2:0:1:1:1 # 1/4 bottom left
ctrl + alt - g : yabai -m window --grid 2:2:1:1:1:1 # 1/4 bottom right

# 1/3
ctrl + alt - a : yabai -m window --grid 1:3:0:0:1:1 # 1/3 left
ctrl + alt - s : yabai -m window --grid 1:3:1:0:1:1 # 1/3 mid
ctrl + alt - d : yabai -m window --grid 1:3:2:0:1:1 # 1/3 right

# 2/3
ctrl + alt - q : yabai -m window --grid 1:3:0:0:2:1 # 2/3 left
ctrl + alt - e : yabai -m window --grid 1:3:1:0:2:1 # 2/3 right
