# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  - trigger: ";td"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ";em"
    replace: "chuangjiaxu@gmail.com"
  - trigger: ";sig"
    replace: |
      Best regards,
      Max
